services:
  postgres:
    image: postgres:16.0-alpine
    container_name: qna_postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

volumes:
  postgres:
    name: qna_postgres
