name: CI

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.0-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: qna_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/qna_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.19.0

      - name: Install JS dependencies
        run: npm install -g yarn && yarn install

      - name: Set up database
        run: bin/rails db:prepare

      - name: Compile Webpacker assets
        run: bin/rails webpacker:compile

      - name: Run tests
        run: bundle exec rspec spec --exclude-pattern "spec/features/**/*_spec.rb"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Security audit dependencies
        run: gem install bundler-audit && bundler-audit --update --ignore CVE-2024-54133
      - name: Security audit application code
        run: gem install brakeman && brakeman -q -w2 --skip-checks EOLRails

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

      - name: Lint Slim files
        run: bundle exec slim-lint app/views/**/*.slim
